group=com.blamejared.ironsmelters
mod_name=IronSmelters
author=Jaredlll08
modid=ironsmelters
avatar=https://media.forgecdn.net/avatars/1446/771/638938497367312557.png
curse_project_id=1349698
curse_homepage=https://www.curseforge.com/minecraft/mc-mods/iron-smelters
modrinth_project_id=il2omh0z
git_repo=https://github.com/jaredlll08/iron-smelters
description=Adds faster Furnaces, Blast Furnaces and Smokers!
item_icon=minecraft:furnace

mod_version=21.1.0
java_version=21
minecraft=1.21.1
fabric_loader=0.17.2
fabric=0.116.6+1.21.1
neoforge=21.1.238
neoforge_loader=[4,)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21-20240613.152323
parchment_version=2024.11.17

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

jei_version=19.51.0.418
prickle_version=21.1.9